server:
  port: 9000
  session:
    #timeout: 1800 
    timeout: 1296000 #1个月  
    cookie: 
      name: SESSION

  tomcat: 
    max-threads: 1000
    min-spare-threads: 200
    accept-count: 1000
    max-connections: 1000
 # connection-timeout: 60
 
spring:
   datasource: 
     name: master
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/lord_say_db
     username: root
     password: liliu 
myPugin: 
  session: 
    myDomainName: null
  projectName: LordSay
  requestAuth: requestAuthDev
  lordSayProjectDomainUrl: http://192.168.11.111
  yunSmsUID: 150241
  yunSmsPWD: rmfbj9
  yunSmsSignName: 【老爷说】
  qiniu:
    accessKey: dGJBFJKfsq-c74QCzTSxLAzPgcDw338-__AKWM8n
    secretKey: yTswXYndF5kVG7LrGb4mX6YqaitNDdjNIpxXIDyk
    bucketName: laoyeshuo
    privateBucketName: laoyeshuovideo
    domain: p2bhwwngu.bkt.clouddn.com
    privateDomain: p2c30vvva.bkt.clouddn.com
  noticeXitongTitle: 系统通知
  noticeTuangouTitle: 团购通知
  noticeBuzuTitle: 团购卡余额不足
  noticeDaozhangTitle: 提现到账通知
  noticeShenqingTitle: 团购申请
  noticeXitongImgUrl: http://p2bhwwngu.bkt.clouddn.com/o_1c5gaqqst68db2j16nno61q3cp.jpg
  noticeTuangouImgUrl: http://p2bhwwngu.bkt.clouddn.com/o_1c5gav4cn173evs35fv1g8f1e6pu.png
  noticeBuzuImgUrl: http://p2bhwwngu.bkt.clouddn.com/o_1c5gb3tvce1e1d7sivg5kr1naq13.png
  noticeDaozhangImgUrl: http://p2bhwwngu.bkt.clouddn.com/o_1c5gb6olh2b49fi11hvqv914c818.png
  noticeShenqingImgUrl: http://p2bhwwngu.bkt.clouddn.com/o_1c5gb9b7411vottl4am19qm7i81d.png
  
  